### ISSUE TITLE
1.20.4 TODO

### ISSUE THREAD

**Issue by kennytv** [PaperSpigot/Paper#10001]
```[tasklist]
### Tasks
- [x] Wait for the adventure pr for 1.20.3 to be merged
- [ ] Check what needs to be adjusted for tick rate command, and change from tacking tick time in ms to ns (prob incremental save patch at min)
- [ ] UUID resource pack api (waiting for adventure)
- [x] ~~new kick event cause~~not needed cause chat chain breaking  doesn't kick
- [x] 0741-Validate-usernames.patch TODO left by owen
- [x] 0751-Kick-on-main-for-illegal-chat.patch TODO left by owen
- [x] Test explosions
- [x] Check if https://github.com/PaperMC/Paper/commit/1d028f3853eaa3bb193d686b9bc213ff8401dd0d#diff-2f0d7107def492370edd3f02de5f9142b4dbf5fa847bdc956e262f5f2fb7f3e6R1687 is correct
- [x] Merge patches/server/1020-Optimise-chunk-tick-iteration.patch stopTimings chunkTicks back into timings-v2
- [ ] Update tps data in `onTickRateChanged` to the current tick rate (otherwise it takes ages to average down/up)
- [x] Check if autosaves are done too often with an increased tick rate
- [ ] Update incremental saving next save tick on tick rate change (make sure it scales with changed tickrates, also when is randomly changed between saves)
- [ ] https://github.com/PaperMC/Paper/pull/10037
```

**Comment by Owen1212055** [comment]
<img width="498" alt="Screenshot 2023-12-06 at 8 30 41 PM" src="https://github.com/PaperMC/Paper/assets/23108066/4161ac85-f322-4c2b-ab52-3b2c7f7e7aff">
For this there is alot of other missing disconnect wraps... why are we not wrapping everything in a task runnable? Confused here.

**Comment by Machine-Maker** [comment]
> For this there is alot of other missing disconnect wraps... why are we not wrapping everything in a task runnable? Confused here.

we actually do have something... or well cb does. Right before the kick event is fired, it checks if its not the primary thread and then moves to the primary thread. But I think this has been around for a while so idk why our fix is needed at all.
