### ISSUE TITLE
1.20.6 Tracking

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#10450]
### Server
- [x] NeutralMob tickInitialPersistenAnger error https://paste.gg/p/anonymous/2215292650c04e9d8b336f7a9f8bdfeb
- [x] Item hovers are broken: `/give @s minecraft:written_book[minecraft:written_book_content={title:"a",author:"a",pages:[]}]`
- [x] check book meta works with adventure
- [x] adventure translations w/StreamCodec
- [x] Look through removed hunks in deobfuscate traces patch
- [x] missing commodore hunk in reflection patch due to commodore changes being after
- [x] https://github.com/PaperMC/Paper/pull/10463
- [x] ~~LootTable#getKey must be deprecated (anonymous loot tables via commands)~~ not immediate concern, not exposed to API
- [x] AttributeModifier constructor passes illegal null for EquipmentSlotGroup
- [x] API: SpawnerEntry$Equipment method javadocs make 0 sense
- [x] ~~MAYBE: Fireball#setDirection changes the acceleration, not direction~~ was OK
- [x] PaperPluginManagerImpl: implement override for loadPlugins(File[])
- [x] check keepalive timeout patch
- [x] Fill Profile Property Events: dropped SkullBlockEntity hunk, there's no GameProfile initially
- [x] Remove unnecessary itemmeta handling (make sure this is still ok to have)
- [x] ItemFlag#HIDE_DESTROYS and ItemFlag#HIDE_PLACED_ON do not function at all
- [x] ~~CanPlaceOn/CanDestroy impl patch isn't applied (its really broken now)~~ Dropped patch, hard break
- [x] ~~ItemMeta#getAsString javadocs wrong (probably should just be deprecated right?)~~ upstream's problem
- [x] Handle Large Packets (encoder logic changed a bit)
- [x] Test ExactChoice recipes in recipe book
- [x] Configurable Keep Spawn Loaded Range (vanilla added something similar w/a different impl)
- [x] old UUID format, now uses codecs, still needed?
- [x] ~~Update itemstack legacy name and lore (uses codecs now, still needed?)~~ dropped
- [x] Check Block onPlace stuff (portal event require entity context)
- [x] Fix Entity Teleportation and cancel velocity if teleported -- do we want to get rid of this patch? yes
- [x] check ignore discounts on merchant offers -- codec magic now
- [x] Root user warning patch can be simplified - the openjdk bug forcing us to use the id binary as a secondary check should be fixed now
- [x] check custom potion mixes patch
- [x] check if MC-253884 and MC-225381 are fixed by mojang, diff didn't apply in misc. mojira tickets patch
- [x] Check if reobf mappings gen needs changes for spigot no longer using ecj
- [x] Check the configurable region file compression
- [x] PlayerShieldDisableEvent - make sure its only needed in the 1 place now.
- [x] Test adventure translations w/creative mode (show item hover event in item_name)
- [ ] EAR patch: "newGoalRate"
- [x] Add back [hunk in improve watchdog support](https://github.com/PaperMC/Paper/commit/c9907c650f160090bf0c1ce9882c57610d5089a1#diff-1547d3cde0478bec15a864f22eb5a2e851393f99ba02209f06a29659d4279a0dL8) when force upgrade patch is back in
- [x] https://github.com/PaperMC/Paper/pull/10454
- [x] ~~Raids#createOrExtendRaid if RaidTrigger event is cancelled, possibly wrong to remove effect~~nope, that's right
- [x] Duplicate itemrarity API
- [x] Test org.bukkit.enchantments.Enchantment#getDamageIncrease(int, org.bukkit.entity.EntityCategory)
- [x] buried treasure and mineshaft custom seeds match vanilla and work with /locate
- [x] dump item command (serialize item to command format)
- [x] ItemFlag#HIDE_ADDITIONAL_TOOLTIP is used for multiple things, breaking functionality
- [x] CraftMetaLeatherArmor#DEFAULT_LEATHER_COLOR handling could be wrong
- [x] hide item meta (anticheat) functionality (now replaced with data component obfuscation: https://github.com/PaperMC/Paper/pull/11817)
- [x] Reconsider ItemMeta#getPlaceableKeys's final life support (now replaced with AdventureModePredicate)

Docs related tasks:
### Docs
- [x] paperweight userdev
- [x] https://github.com/PaperMC/docs/pull/363

**Comment by ham1255** [comment]
https://github.com/PaperMC/Paper/issues/10148 since 1.20.5 is using java 21

**Comment by Atten007** [comment]
Hello,

can the title please be changed to "1.20.6" tracking? Mojang is releasing this version because the developers have found a critical bug that needs to be fixed.

**Comment by Owen1212055** [comment]
1.20.6 isn’t out yet

**Comment by Atten007** [comment]
> 1.20.6 isn’t out yet

Okay, I meant that this should be changed when 1.20.6 is out.

**Comment by MajliTech** [comment]
Hello,
Is there an ETA for when 1.20.6 releases? I have no demands, just asking.
