### ISSUE TITLE
1.21.2 / 1.21.3 Tracking issue

### ISSUE THREAD

**Issue by lynxplay** [PaperSpigot/Paper#11511]
Priority tasks (new, the other list will also have some of those):
- [x] Verify per player mob spawning behavior, especially this change (either it was broken for multiple versions or it is broken now): https://github.com/PaperMC/Paper/commit/3cb16c9d91eb133a9d95605bdb8afc6ed40d6ee9#diff-950deb69c365ce9e698f6f455f174056fc72d2958391fa9bd1ae49e7e029124fL155
- [x] Fix TeleportFlags mapping
- [x] https://github.com/PaperMC/Paper/pull/10675 / https://github.com/PaperMC/Paper/pull/11631
- [x] spark async-profiler update
- [x] https://github.com/PaperMC/Paper/pull/11606
- [x] https://github.com/PaperMC/Paper/pull/11599
---

- [x] ~Check on "Fix entity teleportation and cancel velocity if teleported" since new tp param has delta movement.~ (patch got removed)
- [x] PlayerItemCooldownEvent adoption to cooldown groups (it exposes Material) https://github.com/PaperMC/Paper/pull/11625
- [x] Upstreams (and ours) ItemDamageEvent called for 0 damage https://github.com/PaperMC/Paper/pull/11900
- [x] Check in on PlayerTeleportEndGatewayEvent (might need dimension == targetDimension)
- [x] Fix tripwire disarming not working as intended - do we want this to be configurable still? also this diff is different than ours
- [x] https://github.com/PaperMC/Paper/pull/11605
- [x] https://github.com/PaperMC/Paper/pull/11532
- [x] MCUTILS: look at chunkmap changes around line 555. I removed our changes because I wasn't sure what changed, needs to be looked at!
- [x] timings v2: random line somewhere in serverchunkcache near tick. doesn't matter mutch, entirety of timings needs to be removed
- [x] Check in on EntityZapEvent implementation, heavy overload usage in Mob#convertTo
- [x] Check in on EndermanAttackPlayerEvent - the event may be called in the freeze goal check, sounds unsmart.
- [ ] The entirety of PlayerLaunchProjectileEvent needs review (specifically trident pickup status) see 7c04a31c9. Should work, but check
- [ ] Check on net.minecraft.world.level.material.FlowingFluid#getSpread no longer using a spread cache for initial block state lookup
- [x] Check removed config options.
- [x] w.i.ench.effects.DamageItem > ChangeItemDamage
- [x] Check on Fix Mojang Bugs patch (last good revision was 1dc142534d54bd1ae01060948bd1caad572a9724)
- [x] https://github.com/PaperMC/Paper/pull/11547
- [x] Check on shear api (both shear and drops in event) Also maybe new API to define the used tool?
- [x] Check  Fix possible StackOverflowError for some dispenses for equipables
- [x] Check on resending effects sus stew cancel (no more send active effects? in CB)
- [ ] Rework of map init event fix patch as cache now contains optional
- [x] remove timings
- [ ] Check in on CraftFurnace cook speed multiple / recipe
- [ ] SpawnerEntry$Equipment - LootTable now cannot be null, looks like the entire equipment just needs to be set to null?
- [x] Check GameRule array backed with game rule now feature flagged
- [ ] Remove method with `resendRecipes` param CraftServer#removeRecipe? Currently always has to resend due to index shifts
- [x] configuration option to disable ender pearl chunk loading behaviour #11524
- [x] https://github.com/PaperMC/Paper/pull/11611
- [ ] Investigate calling server tick events during sleep
- [x] add flag to check if the server is sleeping
- [x] https://github.com/PaperMC/Paper/pull/11546
- [x] Tag lifecycleevents might need some rather agressive changes as registry.FREEZE is now *after* post flatten. Resolution is going to be a rename to freeze as the event becomes a "called after all vanilla elements are added". Deprecate freeze for removal, remove in next version.
- [x] https://github.com/PaperMC/Paper/pull/11606
