### ISSUE TITLE
1.21.4 Tracking Issue

### ISSUE THREAD

**Issue by kennytv** [PaperSpigot/Paper#11704]
TODO:

- [x] DistanceManager removeTicketsOnClosing change needed?
- [x] Check on Player spawnParticle force option - correctly used in packet?
- [x] Check Leashable#dropLeash changes, mojang seperated the dropItem call into drop/Remove methods, calling static util
- [x] PlayerPickItemEvent needs testing (are source and target slots correct and can be changed)
- [x] Finish up CustomModelData API
- [x] https://bugs.mojang.com/browse/MC-273635 fixed, see mc fixes issue
