### ISSUE TITLE
1.19 Tracking issue

### ISSUE THREAD

**Issue by electronicboy** [PaperSpigot/Paper#7780]
1.19, or, whatever comes before

- [x] Remove filtered sign text patch (Mojang added datafixers to do the same)
- [x] Remove Painting line from `Fix-Entity-Position-Desync.patch`
- [x] Dont resend paintings when modifying motive. [See here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/64c15270e76475e68b2167d4bfba162a4a827fe0#src/main/java/org/bukkit/craftbukkit/entity/CraftPainting.java)
- [x] add `-Ppaperweight.filter-patches=false` to upstreamMerge.sh script to not cleanup patch indices
- [ ] Sort out adventure identities and chat signing
- [x] rename paper config slime swamp biome spawn checks. (server now uses a tag to check if slime can spawn on the surface)
- [x] Fix missing chunks due to integer overflow

## API
- [x] Make tadpole extend Bucketable
- [x] get last death location (upstream PR)
- [x] Implement Keyed on Cat$Type
- [x] Test PlayerLoomPatternSelectEvent

**Comment by Spottedleaf** [comment]
~~scarfacered — Today at 5:53 PM
[here](https://github.com/PaperMC/Paper/compare/3a0b9487d462...c515eb9a0857#diff-9d59683564b11d7f9a711c5a22c23cf0f960ca07889526a594608bff3bc2075dR84-R89) was world != null unintentionally flipped here?~~
Fixed in 68b585fba

**Comment by Spottedleaf** [comment]
should kick players if packet handling fails, instead of log - just lets players abuse potential problems or spam logs

**Comment by kennytv** [comment]
@Spottedleaf
* ~~check https://github.com/PaperMC/Paper/commit/d28b20944bf24dee5681b42d212d6fe98ccd09a6#diff-d2b96d95ddbbb1064cbd99424aac93b350b95caad3d5379387bbb2ed67339b65R5099 (opening the collapsed patch will jump to the line)~~, also check removed folder for leaf patches,
* ~~and why you removed this method https://github.com/PaperMC/Paper/commit/1d5b298c19793068a60f176dff697f89e89fb56e#diff-fcc65168e0146f2c07d2167c145c4880cff2c61f838f99b52a1df7b880009895R1334~~
* ~~Level propagator patch is butched~~

@jpenilla check if `Vanilla-command-permission-fixes` is fine

Chat:
* AdventureComponent
* sendMessage methods using Identity
* ~~decide on when to use system vs. player message (unsigned player messages with broken format are pointless)~~

**Comment by aurorasmiles** [comment]
~~@Spottedleaf  Asynchronous chunk IO and loading appears to cause this issue to appear.~~

~~The easiest way to reproduce this is to /locate structure and load those chunks, it'll start logging those errors especially in villages.
`[13:10:32] [Server thread/ERROR]: Failed to read POI section: Can't access registry ResourceKey[minecraft:root / minecraft:point_of_interest_type]`~~
fixed in https://github.com/PaperMC/Paper/commit/a93aa05bf8ed7d293f4ecba432491ab481eec05d

**Comment by kennytv** [comment]
~~The bundler jar being broken~~
- jmp is looking into this, don't create new paperweight release yet

**Comment by Machine-Maker** [comment]
light related issue: https://pastes.dev/7l8pWSSx7c
Only happens to pre-existing worlds. New worlds are just fine

**Comment by kennytv** [comment]
~~Look at feature seed patch~~
~~Move command registration out of PaperConfig~~
~~Make configurable messages use minimessage format~~

**Comment by aurorasmiles** [comment]
A few people noticed that the time between the first `Preparing level "world"` when generating a new world and the actual `Preparing start region for dimension minecraft:overworld` has noticably incread (almost doubled for me) with the current experimental build, not sure if that is something worth looking into/known
