### ISSUE TITLE
Paper 1.19.4 tracking issue

### ISSUE THREAD

**Issue by kennytv** [PaperSpigot/Paper#8966]
- [x] Test Timings icon display
- [x] Previously changed ClientboundStatusResponsePacket typeadapter for adventure components; would probably need a codec now lmao
- [x] Upstream update, setPlayerProfile patch
- [x] Optimize hoppers patch
- [x] Check if these two hunks need porting https://github.com/PaperMC/Paper/commit/18d51375b8a3fade82b245db097f856b81cb0566#diff-b4219a2aa24d87d2d0071000b795377a7c93f38b8aed8b13c45f450fdf081434L24
- [x] Not related to this update, but what happens if dummyBlockstate for example is null (and should it call an event?) in `Add CompostItemEvent and EntityCompostItemEvent`
- [x] Make sure hopper minecarts don't have cooldowns any more (there is related API)
- [ ] Partial apply of Optimize NetworkManager Exception Handling (also partial of ip logging config option patch)

**Comment by Machine-Maker** [comment]
LivingEntity#setHurtDirection(float) doesn't work on anything except players now. The field tracking it was moved from LivingEntity to Player
