### ISSUE TITLE
1.20 tracking issue

### ISSUE THREAD

**Issue by kennytv** [PaperSpigot/Paper#9268]
- [x] `public final int getEffectiveViewDistance() {` in ChunkMap - is +0 correct now?
- [x] `CraftSign#openSign` needs to call `SignBlockEntity#setAllowedPlayerEditor` to allow editing.
- [x] Reobf mappings patch
- [x] Figure out Block#isBurnable, Material#isFlammable, Material#isBurnable
- [x] ~~Check BlockCollisions return this.resultProvider.apply in Optimize Collision to not load chunks~~ (replaced by moonrise)
- [x] SignCommandPreprocessEvent side
- [x] SmithingRecipe should throw an error when used, as it does nothing now **just deprecated insstead**
- [x] Fix upstreams block state factories -- handle sussy sand/gravel
- [x] check Optimise collision checking in player move packet handling, why is there no longer an absMove call
- [x] EntityFertilizeEggEvent call on breed https://github.com/PaperMC/Paper/pull/9280
- [x] check hopper canMergeItems
- [x] Sign#isEditable and Sign#setEditable should maybe be deprecated and rethought with waxing and editing player UUID https://github.com/PaperMC/Paper/pull/9291
- [x] Allow skipping writing of comments to server.properties (write logic changed)
- [x] Test out #setListenerRange on SculkSensor
- [x] Test #regenerateChunk
