### ISSUE TITLE
1.20.2 Tracking

### ISSUE THREAD

**Issue by Machine-Maker** [PaperSpigot/Paper#9742]
- [x] legacy ping handler changes (2 patches)
- [x] Revisit 0653-Add-missing-team-sidebar-display-slots.patch if needed. https://github.com/PaperMC/Paper/pull/9746
- [ ] Test 0658-Add-more-advancement-API.patch. Advancement were completely re-done https://github.com/PaperMC/Paper/pull/9745 once runnable
- [x] ip logging migration https://github.com/PaperMC/Paper/pull/9748
- [ ] Connection#runOnceConnected+send+flushChannel race condition
- [x] Figure out TrackingRangeY
- [x] CraftMushroomCow needs api for multiple effects, instead of just one https://github.com/PaperMC/Paper/issues/9749
- [x] DisplaySlotTest implement testMinecraftToBukkitDisplaySlots https://github.com/PaperMC/Paper/pull/9746
